server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudtest?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123abc

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.zshan.springcloud.entities #所有Entity别名类所在包

eureka:
  client:
    register-with-eureka: true #表示是否将自己注册金EurekaServer 默认为true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2